// Ikony aplikacji — Phosphor (waga `regular`), zgodnie z briefem „edytorski gastro".
//
// Warstwa adaptera: eksportujemy Phosphora pod nazwami, których używa cała apka
// (dziedzictwo po lucide-react). Dzięki temu podmiana biblioteki to jedna zmiana
// importu w pliku, a nie 68 zmian nazw w 61 plikach — i kolejna podmiana też
// będzie kosztować tylko ten plik.
//
// Uwaga o rozmiarze: Phosphor renderuje <svg width="1em" height="1em">, ale
// tailwindowe klasy (`w-4 h-4`, `size-4`) to CSS, które wygrywa z atrybutem —
// więc dotychczasowe rozmiary działają bez zmian. Kolor: `fill="currentColor"`.
//
// NIE importuj `lucide-react` w nowym kodzie. Brakującą ikonę dopisz tutaj.
export {
  Warning as AlertTriangle,
  ArrowDown,
  ArrowDownRight,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  ChartBar as BarChart3,
  Bell,
  Buildings as Building2,
  Calculator,
  CalendarBlank as Calendar,
  Camera,
  Check,
  CheckCircle as CheckCircle2,
  CaretDown as ChevronDown,
  CaretLeft as ChevronLeft,
  CaretRight as ChevronRight,
  CaretUp as ChevronUp,
  CaretUpDown as ChevronsUpDown,
  Circle,
  Clock,
  Copy,
  DownloadSimple as Download,
  PencilSimple as Edit2,
  ArrowSquareOut as ExternalLink,
  Eye,
  EyeSlash as EyeOff,
  FileText,
  GitDiff as GitCompare,
  DotsSixVertical as GripVertical,
  House as Home,
  Image as ImageIcon,
  StackSimple as Layers,
  SquaresFour as LayoutDashboard,
  ChartLine as LineChart,
  CircleNotch as Loader2,
  CircleNotch as Loader2Icon,
  Envelope as Mail,
  Minus,
  Moon,
  DotsThree as MoreHorizontal,
  Package,
  SidebarSimple as PanelLeftIcon,
  PencilSimple as Pencil,
  Percent,
  Phone,
  Plug,
  Plus,
  ArrowsClockwise as RefreshCw,
  ArrowCounterClockwise as RotateCcw,
  FloppyDisk as Save,
  Scan as ScanLine,
  MagnifyingGlass as Search,
  ShieldWarning as ShieldAlert,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Sparkle as Sparkles,
  Sun,
  Tag,
  Trash as Trash2,
  TrendDown as TrendingDown,
  TrendUp as TrendingUp,
  Trophy,
  UploadSimple as Upload,
  X,
  Lightning as Zap,

  SortAscending as ArrowDownAZ,
  SortDescending as ArrowUpZA,
  ChartBar as BarChart2,
  BellRinging as BellRing,
  Robot as Bot,
  CalendarDots as CalendarDays,
  Checks as CheckCheck,
  CheckSquare,
  CaretDown as ChevronDownIcon,
  CaretLeft as ChevronLeftIcon,
  CaretRight as ChevronRightIcon,
  FileArrowDown as FileCheck2,
  FileCode,
  FileXls as FileSpreadsheet,
  ClockCounterClockwise as History,
  Bed as Hotel,
  Tray as Inbox,
  Key as KeyRound,
  Lightbulb,
  List,
  List as Menu,
  Lock,
  SignOut as LogOut,
  Play,
  Receipt,
  PaperPlaneTilt as Send,
  HardDrives as Server,
  Gear as Settings,
  ShieldSlash as ShieldOff,
  Storefront as Store,
  Truck,
  Users,
  ForkKnife as UtensilsCrossed,

  // Ikony kategorii produktów (patrz lib/category-icons.tsx). Zastąpiły emoji —
  // emoji ciągnęły „look AI" i odstawały od reszty interfejsu.
  Acorn,
  Bread,
  Cake,
  Carrot,
  Cheese,
  Cow,
  Cube,
  Drop,
  Egg,
  Fish,
  Jar,
  PintGlass,
  Snowflake,
  SprayBottle,
  Toolbox,
  Wine,
} from "@phosphor-icons/react";

export type { Icon as IconComponent, IconProps } from "@phosphor-icons/react";
