import {
  KsefAuthError,
  KsefError,
  KsefNetworkError,
  KsefRateLimitError,
  KsefServerError,
} from "./errors";

export const KSEF_PRODUCTION_BASE_URL = "https://ksef.mf.gov.pl/api/v2";

export interface KsefSession {
  /** Session token returned by KSeF — passed as Bearer on subsequent calls. */
  sessionToken: string;
  /** NIP of the authenticated context. */
  nip: string;
  /** Base URL of the KSeF environment (defaults to production). */
  baseUrl: string;
  /** Issuance timestamp (ms). */
  issuedAt: number;
}

export interface KsefInvoiceListItem {
  ksefReferenceNumber: string;
  invoiceNumber: string;
  issueDate: string;
  sellerNip: string;
  buyerNip: string;
  invoicingMode?: string;
  invoiceType?: string;
}

export interface ListInvoicesParams {
  subjectType: "buyer" | "seller";
  nip: string;
  dateFrom: string; // ISO date (YYYY-MM-DD) or full ISO datetime
  dateTo: string;
  pageOffset?: number;
  pageSize?: number;
}

export interface ListInvoicesResult {
  invoices: KsefInvoiceListItem[];
  hasMore: boolean;
  nextOffset: number;
}

type Logger = {
  info: (obj: Record<string, unknown>, msg?: string) => void;
  warn: (obj: Record<string, unknown>, msg?: string) => void;
  error: (obj: Record<string, unknown>, msg?: string) => void;
};

const NOOP_LOGGER: Logger = {
  info: () => {},
  warn: () => {},
  error: () => {},
};

export interface KsefClientOptions {
  baseUrl?: string;
  logger?: Logger;
  fetchImpl?: typeof fetch;
  /** Max retries for 429 / 5xx (default 3). */
  maxRetries?: number;
}

function maskToken(token: string): string {
  if (token.length <= 4) return "****";
  return `****${token.slice(-4)}`;
}

async function sleep(ms: number): Promise<void> {
  return new Promise((r) => setTimeout(r, ms));
}

/**
 * Low-level KSeF 2.0 client.
 *
 * NOTE on KSeF 2.0 authorization: the Ministry of Finance exposes several
 * authorization flows. This client uses the **authorization token** flow:
 * a token generated by the taxpayer in the KSeF web application is exchanged
 * (along with the NIP) for a short-lived **session token** that is then sent
 * as `Authorization: Bearer ...` on subsequent calls. Exact endpoint paths
 * are kept in named constants so they can be adjusted if the published API
 * surface changes without rewriting the call sites.
 */
export class KsefClient {
  private readonly baseUrl: string;
  private readonly logger: Logger;
  private readonly fetchImpl: typeof fetch;
  private readonly maxRetries: number;

  constructor(opts: KsefClientOptions = {}) {
    this.baseUrl = (opts.baseUrl ?? KSEF_PRODUCTION_BASE_URL).replace(/\/+$/, "");
    this.logger = opts.logger ?? NOOP_LOGGER;
    this.fetchImpl = opts.fetchImpl ?? fetch;
    this.maxRetries = opts.maxRetries ?? 3;
  }

  private async request<T>(
    path: string,
    init: RequestInit & { responseType?: "json" | "text" } = {},
  ): Promise<T> {
    const url = `${this.baseUrl}${path}`;
    const { responseType = "json", headers, ...rest } = init;

    const mergedHeaders = new Headers(headers ?? {});
    if (!mergedHeaders.has("Accept")) {
      mergedHeaders.set("Accept", responseType === "json" ? "application/json" : "application/xml, text/xml, */*");
    }

    let lastErr: unknown = null;
    for (let attempt = 0; attempt <= this.maxRetries; attempt++) {
      try {
        const res = await this.fetchImpl(url, { ...rest, headers: mergedHeaders });

        if (res.status === 401 || res.status === 403) {
          throw new KsefAuthError(
            `KSeF odrzucił żądanie (HTTP ${res.status}). Sprawdź token i NIP w ustawieniach.`,
          );
        }

        if (res.status === 429) {
          if (attempt < this.maxRetries) {
            const retryAfter = Number(res.headers.get("Retry-After")) || 2 ** attempt;
            this.logger.warn({ url: path, attempt, retryAfter }, "KSeF 429, retrying");
            await sleep(retryAfter * 1000);
            continue;
          }
          throw new KsefRateLimitError();
        }

        if (res.status >= 500) {
          if (attempt < this.maxRetries) {
            this.logger.warn({ url: path, attempt, status: res.status }, "KSeF 5xx, retrying");
            await sleep(2 ** attempt * 500);
            continue;
          }
          const body = await res.text().catch(() => "");
          throw new KsefServerError(`KSeF zwrócił HTTP ${res.status}: ${body.slice(0, 200)}`);
        }

        if (!res.ok) {
          const body = await res.text().catch(() => "");
          throw new KsefError(`KSeF HTTP ${res.status}: ${body.slice(0, 200)}`);
        }

        if (responseType === "text") {
          return (await res.text()) as unknown as T;
        }
        return (await res.json()) as T;
      } catch (err) {
        if (err instanceof KsefError) throw err;
        lastErr = err;
        if (attempt < this.maxRetries) {
          this.logger.warn({ url: path, attempt, err: String(err) }, "KSeF network error, retrying");
          await sleep(2 ** attempt * 500);
          continue;
        }
        throw new KsefNetworkError(
          `Błąd sieci podczas wywołania KSeF: ${(err as Error).message}`,
          err,
        );
      }
    }
    throw new KsefNetworkError("Wyczerpano liczbę prób połączenia z KSeF.", lastErr);
  }

  /**
   * Exchange an authorization token (generated by the taxpayer in the KSeF
   * web application) for a session token bound to a given NIP.
   */
  async authenticate(nip: string, token: string): Promise<KsefSession> {
    this.logger.info({ nip, token: maskToken(token) }, "KSeF authenticate");

    const res = await this.request<{
      sessionToken?: { token?: string; value?: string };
      token?: string;
      value?: string;
    }>(`/auth/token/init`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        nip,
        contextIdentifier: { type: "onip", identifier: nip },
        authorizationToken: token,
      }),
    });

    const sessionToken =
      res.sessionToken?.token ??
      res.sessionToken?.value ??
      res.token ??
      res.value;

    if (!sessionToken) {
      throw new KsefAuthError(
        "KSeF nie zwrócił tokena sesji. Sprawdź token autoryzacyjny i NIP w ustawieniach.",
      );
    }

    return {
      sessionToken,
      nip,
      baseUrl: this.baseUrl,
      issuedAt: Date.now(),
    };
  }

  async listInvoices(
    session: KsefSession,
    params: ListInvoicesParams,
  ): Promise<ListInvoicesResult> {
    const pageOffset = params.pageOffset ?? 0;
    const pageSize = params.pageSize ?? 100;

    const res = await this.request<{
      invoiceHeaderList?: Array<Record<string, unknown>>;
      invoices?: Array<Record<string, unknown>>;
      hasMore?: boolean;
      numberOfElements?: number;
      totalElements?: number;
    }>(`/invoices/query?PageOffset=${pageOffset}&PageSize=${pageSize}`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${session.sessionToken}`,
      },
      body: JSON.stringify({
        queryCriteria: {
          subjectType: params.subjectType,
          type: "incremental",
          acquisitionTimestampThresholdFrom: params.dateFrom.includes("T")
            ? params.dateFrom
            : `${params.dateFrom}T00:00:00.000Z`,
          acquisitionTimestampThresholdTo: params.dateTo.includes("T")
            ? params.dateTo
            : `${params.dateTo}T23:59:59.999Z`,
        },
      }),
    });

    const raw = res.invoiceHeaderList ?? res.invoices ?? [];
    const invoices: KsefInvoiceListItem[] = raw.map((row) => ({
      ksefReferenceNumber:
        (row.ksefReferenceNumber as string) ??
        (row.ksefNumber as string) ??
        (row.referenceNumber as string),
      invoiceNumber: (row.invoiceNumber as string) ?? (row.invoicingNumber as string) ?? "",
      issueDate: (row.issueDate as string) ?? (row.invoiceDate as string) ?? "",
      sellerNip:
        (row.sellerNip as string) ??
        ((row.subjectBy as Record<string, unknown>)?.identifier as string) ??
        "",
      buyerNip:
        (row.buyerNip as string) ??
        ((row.subjectTo as Record<string, unknown>)?.identifier as string) ??
        "",
      invoicingMode: row.invoicingMode as string | undefined,
      invoiceType: row.invoiceType as string | undefined,
    })).filter((i) => i.ksefReferenceNumber);

    const total = res.totalElements ?? invoices.length + pageOffset;
    const nextOffset = pageOffset + invoices.length;
    const hasMore = res.hasMore ?? nextOffset < total;

    return { invoices, hasMore, nextOffset };
  }

  async getInvoiceXml(session: KsefSession, ksefReferenceNumber: string): Promise<string> {
    return this.request<string>(`/invoices/${encodeURIComponent(ksefReferenceNumber)}`, {
      method: "GET",
      headers: {
        Authorization: `Bearer ${session.sessionToken}`,
      },
      responseType: "text",
    });
  }
}
