uploads = []

[[generated]]
id = "PZ2Fgt7fo_Ee7vXqZw1va"
uri = "file://artifacts/checkit-mobile/assets/images/icon.png"
type = "image"
title = "generated_image"

[[outputs]]
id = "MIK1ytWi62gtyahCBK89I"
uri = "file://categories-reports.tar.gz"
type = "unspecified"
title = "categories.ts + reports.tsx"

[[outputs]]
id = "HakfhTDxnJCrU7Zku6WRs"
uri = "file://categories.txt"
type = "text"
title = "categories.ts"

[[outputs]]
id = "TgB-S-n0hxgDcpIWkjkST"
uri = "file://reports.txt"
type = "text"
title = "reports.tsx"

[[outputs]]
id = "QbIOS88dSmJbQfALMQ3rG"
uri = "file://kod-do-oceny.md"
type = "text"
title = "categories.ts + reports.tsx"
