// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/home-variants/Dynamic.tsx": () => import("../components/mockups/home-variants/Dynamic.tsx"),
  "./components/mockups/home-variants/Editorial.tsx": () => import("../components/mockups/home-variants/Editorial.tsx")
};
