const colors = {
  light: {
    text: "#0b1016",
    tint: "#14b8a6",
    background: "#ffffff",
    foreground: "#0b1016",
    card: "#ffffff",
    cardForeground: "#0b1016",
    primary: "#14b8a6",
    primaryForeground: "#ffffff",
    secondary: "#f0fafa",
    secondaryForeground: "#091e1d",
    muted: "#f0fafa",
    mutedForeground: "#6b8785",
    accent: "#14b8a6",
    accentForeground: "#ffffff",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#dff0ee",
    input: "#dff0ee",
    success: "#10b981",
    successForeground: "#ffffff",
    warning: "#f59e0b",
    warningForeground: "#ffffff",
  },
  dark: {
    text: "#f2f4f6",
    tint: "#14b8a6",
    background: "#060c1f",
    foreground: "#f2f4f6",
    card: "#0a1020",
    cardForeground: "#f2f4f6",
    primary: "#14b8a6",
    primaryForeground: "#ffffff",
    secondary: "#152030",
    secondaryForeground: "#f0f2f8",
    muted: "#152030",
    mutedForeground: "#b4bac8",
    accent: "#14b8a6",
    accentForeground: "#ffffff",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#152030",
    input: "#152030",
    success: "#10b981",
    successForeground: "#ffffff",
    warning: "#f59e0b",
    warningForeground: "#ffffff",
  },
  radius: 10,
};

export default colors;
